# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import servicio_pb2 as servicio__pb2


class FarmaceuticaStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Listo = channel.unary_unary(
                '/Farmaceutica/Listo',
                request_serializer=servicio__pb2.Nulo.SerializeToString,
                response_deserializer=servicio__pb2.Nulo.FromString,
                )
        self.AltaTipoMedicamento = channel.unary_unary(
                '/Farmaceutica/AltaTipoMedicamento',
                request_serializer=servicio__pb2.Tipo.SerializeToString,
                response_deserializer=servicio__pb2.Confirmacion.FromString,
                )
        self.BajaTipoMedicamento = channel.unary_unary(
                '/Farmaceutica/BajaTipoMedicamento',
                request_serializer=servicio__pb2.Tipo.SerializeToString,
                response_deserializer=servicio__pb2.Confirmacion.FromString,
                )
        self.AltaMedicamento = channel.unary_unary(
                '/Farmaceutica/AltaMedicamento',
                request_serializer=servicio__pb2.Medicamento.SerializeToString,
                response_deserializer=servicio__pb2.Confirmacion.FromString,
                )
        self.ConsultaMedicamentoPorTipo = channel.unary_unary(
                '/Farmaceutica/ConsultaMedicamentoPorTipo',
                request_serializer=servicio__pb2.ConsultaTipo.SerializeToString,
                response_deserializer=servicio__pb2.ListaMedicamentos.FromString,
                )
        self.ConsultaMedicamentoPorNombreComercial = channel.unary_unary(
                '/Farmaceutica/ConsultaMedicamentoPorNombreComercial',
                request_serializer=servicio__pb2.ConsultaTipo.SerializeToString,
                response_deserializer=servicio__pb2.ListaMedicamentos.FromString,
                )
        self.ListaProductos = channel.unary_unary(
                '/Farmaceutica/ListaProductos',
                request_serializer=servicio__pb2.Nulo.SerializeToString,
                response_deserializer=servicio__pb2.ListaMedicamentos.FromString,
                )
        self.EsPrioritario = channel.unary_unary(
                '/Farmaceutica/EsPrioritario',
                request_serializer=servicio__pb2.ConsultaTipo.SerializeToString,
                response_deserializer=servicio__pb2.RespuestaCodigo.FromString,
                )
        self.Verificar = channel.unary_unary(
                '/Farmaceutica/Verificar',
                request_serializer=servicio__pb2.ConsultaTipo.SerializeToString,
                response_deserializer=servicio__pb2.RespuestaCodigo.FromString,
                )


class FarmaceuticaServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Listo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AltaTipoMedicamento(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BajaTipoMedicamento(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AltaMedicamento(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConsultaMedicamentoPorTipo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConsultaMedicamentoPorNombreComercial(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListaProductos(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EsPrioritario(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Verificar(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FarmaceuticaServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Listo': grpc.unary_unary_rpc_method_handler(
                    servicer.Listo,
                    request_deserializer=servicio__pb2.Nulo.FromString,
                    response_serializer=servicio__pb2.Nulo.SerializeToString,
            ),
            'AltaTipoMedicamento': grpc.unary_unary_rpc_method_handler(
                    servicer.AltaTipoMedicamento,
                    request_deserializer=servicio__pb2.Tipo.FromString,
                    response_serializer=servicio__pb2.Confirmacion.SerializeToString,
            ),
            'BajaTipoMedicamento': grpc.unary_unary_rpc_method_handler(
                    servicer.BajaTipoMedicamento,
                    request_deserializer=servicio__pb2.Tipo.FromString,
                    response_serializer=servicio__pb2.Confirmacion.SerializeToString,
            ),
            'AltaMedicamento': grpc.unary_unary_rpc_method_handler(
                    servicer.AltaMedicamento,
                    request_deserializer=servicio__pb2.Medicamento.FromString,
                    response_serializer=servicio__pb2.Confirmacion.SerializeToString,
            ),
            'ConsultaMedicamentoPorTipo': grpc.unary_unary_rpc_method_handler(
                    servicer.ConsultaMedicamentoPorTipo,
                    request_deserializer=servicio__pb2.ConsultaTipo.FromString,
                    response_serializer=servicio__pb2.ListaMedicamentos.SerializeToString,
            ),
            'ConsultaMedicamentoPorNombreComercial': grpc.unary_unary_rpc_method_handler(
                    servicer.ConsultaMedicamentoPorNombreComercial,
                    request_deserializer=servicio__pb2.ConsultaTipo.FromString,
                    response_serializer=servicio__pb2.ListaMedicamentos.SerializeToString,
            ),
            'ListaProductos': grpc.unary_unary_rpc_method_handler(
                    servicer.ListaProductos,
                    request_deserializer=servicio__pb2.Nulo.FromString,
                    response_serializer=servicio__pb2.ListaMedicamentos.SerializeToString,
            ),
            'EsPrioritario': grpc.unary_unary_rpc_method_handler(
                    servicer.EsPrioritario,
                    request_deserializer=servicio__pb2.ConsultaTipo.FromString,
                    response_serializer=servicio__pb2.RespuestaCodigo.SerializeToString,
            ),
            'Verificar': grpc.unary_unary_rpc_method_handler(
                    servicer.Verificar,
                    request_deserializer=servicio__pb2.ConsultaTipo.FromString,
                    response_serializer=servicio__pb2.RespuestaCodigo.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Farmaceutica', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Farmaceutica(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Listo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Farmaceutica/Listo',
            servicio__pb2.Nulo.SerializeToString,
            servicio__pb2.Nulo.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AltaTipoMedicamento(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Farmaceutica/AltaTipoMedicamento',
            servicio__pb2.Tipo.SerializeToString,
            servicio__pb2.Confirmacion.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def BajaTipoMedicamento(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Farmaceutica/BajaTipoMedicamento',
            servicio__pb2.Tipo.SerializeToString,
            servicio__pb2.Confirmacion.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AltaMedicamento(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Farmaceutica/AltaMedicamento',
            servicio__pb2.Medicamento.SerializeToString,
            servicio__pb2.Confirmacion.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ConsultaMedicamentoPorTipo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Farmaceutica/ConsultaMedicamentoPorTipo',
            servicio__pb2.ConsultaTipo.SerializeToString,
            servicio__pb2.ListaMedicamentos.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ConsultaMedicamentoPorNombreComercial(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Farmaceutica/ConsultaMedicamentoPorNombreComercial',
            servicio__pb2.ConsultaTipo.SerializeToString,
            servicio__pb2.ListaMedicamentos.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListaProductos(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Farmaceutica/ListaProductos',
            servicio__pb2.Nulo.SerializeToString,
            servicio__pb2.ListaMedicamentos.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def EsPrioritario(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Farmaceutica/EsPrioritario',
            servicio__pb2.ConsultaTipo.SerializeToString,
            servicio__pb2.RespuestaCodigo.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Verificar(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Farmaceutica/Verificar',
            servicio__pb2.ConsultaTipo.SerializeToString,
            servicio__pb2.RespuestaCodigo.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
